config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: :omniauth_callbacks
  }
  root controller: :tasks, action: :index

  resources :tasks, only: [:new, :create, :show, :update]
end

app/models/task.rb
class Task < ApplicationRecord  
    validates_presence_of :title, :description, :budget, :location, :state

    belongs_to :user

    state_machine :state, initial: :open do 
        
        event :receive_bid do 
            transition :open => :pending
        end

        event :accept_bid do
            transition [:open, :pending] => :in_production
        end

        event :closed do 
            transition [:in_production] => :closed
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name

  has_many :tasks
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
          user_params.permit( :name, :email, :password, :password_confirmation)
        end
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController 

    def facebook 
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
        else
          session['devise.facebook_data'] = resquest.env('omniauth.auth')
          redirect_to new_user_registration_path
        end

    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.create(task_params)
    if @task.persisted?
      redirect_to root_path, notice: "Task successfully created"
    else
      flash[:error] = 'Your Task could not be created'
      render :new
    end
  end

  def update 
    @task = Task.find(params[:id])
    if params[:event] == 'receive_bid'
      @task.receive_bid
    end
    NotificationsMailer.with(doer: current_user, task: @task).task_started.deliver_now
    render json: {message: "Task poster has been notified - your interest in working on #{@task.title} has been submitted.", task: @task}
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :budget, :location, :state)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', http: {equiv: "Content-Type"}}/
    %title Boilerplate
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', data: {'turbolinks-track' => 'reload'}
    = javascript_include_tag 'application', data: {'turbolinks-track' => 'reload'}
  %body
    - unless current_user 
      = link_to 'Log in with Facebook', user_facebook_omniauth_authorize_path
    = notice
    = flash[:error]
    = yield

app/views/tasks/index.html.haml
%h1 Tasks#index
%p Find me in app/views/tasks/index.html.haml

= link_to "New Task", new_task_path
- @tasks.each do |task|
    = link_to task.title, task_path(task)
    %p= task.location
    %p= task.budget

app/views/tasks/new.html.haml
= form_with model: @task, remote: false do |form|
    = form.label :title
    = form.text_field :title
    %br
    = form.label :description
    = form.text_area :description
    %br
    = form.label :budget
    = form.text_field :budget
    %br
    = form.label :location
    = form.text_field :location
    %br
    = form.submit 'Post Task'

app/views/tasks/show.html.haml
%h2= @task.title
%p= @task.description
%p= @task.location
%p= @task.budget
%p#state= @task.state.titleize

= link_to "Let's do it", task_path(@task, event: :receive_bid), method: :put, remote: true, id: 'lets-do-it'
= link_to "Send Counter offer", '#'